version: '3.5'
services:
  db:
    container_name: movies-api-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-graphql-api
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - '${PORT}:${PORT}'
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - ./src:/app/src