version: '3.5'
services:
  movies-api-postgres:
    container_name: movies-api-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ENVIRONMENT=development
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
    networks:
      - movies
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: movies-graphql-api
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - '${PORT}:${PORT}'
    env_file: .env
    restart: always
    depends_on:
      - movies-api-postgres
    command: npm run start:dev
    volumes:
      - ./src:/app/src
    networks:
      - movies

networks:
  movies:
    driver: bridge