Description: Cloudformation template to deploy a database on AWS RDS.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID in which the infrastructure will be deployed.

  DatabaseUser:
    Default: startupadmin
    Type: String
    Description: Database admin account name
    MinLength: 5
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Name must begin with a letter and contain only alphanumeric characters

  DatabasePassword:
    NoEcho: true
    Type: String
    Description: Database admin account password
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Password must contain only alphanumeric characters
  
  EcsSecurityGroup:
    Description: "ECS security group"
    Type: "AWS::EC2::SecurityGroup::Id"

Resources:
  MoviesDb:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      DBName: moviesdb
      Port: 5432
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      VPCSecurityGroups: !Ref DbSecurityGroup
  
  DbSecurityGroupFromAppPostgreSqlIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DbSecurityGroup
      IpProtocol: tcp
      ToPort: 5432
      FromPort: 5432
      SourceSecurityGroupId: !Ref EcsSecurityGroup

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: movies-postgre-db-sg
      GroupDescription: Enable access to the RDS DB
      VpcId: !Ref VpcId
